---
release:
  branches:
    - main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  -
    - 'semantic-release-circleci-orb'
    - orbName: pedrotroller/octokit
      orbPath: '@orb.yml'
