---
version: 2.1

executorType: machine

orbs:
  cli: circleci/circleci-cli@0.1.8
  octokit:
    examples:
      comment-on-an-issue:
        description: "Comment on an issue"
        usage:
          version: 2.1
          executorType: machine
          orbs:
            octokit: pedrotroller/octokit@x.y.z
          jobs:
            your-job:
              docker:
                - image: circleci/node
              steps:
                - octokit/script:
                    script: |
                      github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'Thanks for reporting!'
                      })
          workflows:
            your-workflow:
              jobs:
                - your-job
      apply-a-label-to-an-issue:
        description: "Apply a label to an issue"
        usage:
          version: 2.1
          executorType: machine
          orbs:
            octokit: pedrotroller/octokit@x.y.z
          jobs:
            your-job:
              docker:
                - image: circleci/node
              steps:
                - octokit/script:
                    script: |
                      github.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ['Triage']
                      })
          workflows:
            your-workflow:
              jobs:
                - your-job
      welcome-a-first-time-contributor:
        description: "Welcome a first time contributor"
        usage:
          version: 2.1
          executorType: machine
          orbs:
            octokit: pedrotroller/octokit@x.y.z
          jobs:
            your-job:
              docker:
                - image: circleci/node
              steps:
                - octokit/script:
                    script: |
                      // Get a list of all issues created by the PR opener
                      // See: https://octokit.github.io/rest.js/#pagination
                      const creator = context.payload.sender.login
                      const opts = github.issues.listForRepo.endpoint.merge({
                        ...context.issue,
                        creator,
                        state: 'all'
                      })
                      const issues = await github.paginate(opts)

                      for (const issue of issues) {
                        if (issue.number === context.issue.number) {
                          continue
                        }

                        if (issue.pull_request) {
                          return // Creator is already a contributor.
                        }
                      }

                      await github.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: 'Welcome, new contributor!'
                      })
          workflows:
            your-workflow:
              jobs:
                - your-job
      download-data-from-a-url:
        description: "Download data from a url"
        usage:
          version: 2.1
          executorType: machine
          orbs:
            octokit: pedrotroller/octokit@x.y.z
          jobs:
            your-job:
              docker:
                - image: circleci/node
              steps:
                - octokit/script:
                    script: |
                      const diff_url = context.payload.pull_request.diff_url
                      const result = await github.request(diff_url)
                      console.log(result)
          workflows:
            your-workflow:
              jobs:
                - your-job
      run-custom-graphql-queries:
        description: "Run custom GraphQL queries"
        usage:
          version: 2.1
          executorType: machine
          orbs:
            octokit: pedrotroller/octokit@x.y.z
          jobs:
            your-job:
              docker:
                - image: circleci/node
              steps:
                - octokit/script:
                    script: |
                      const query = `query($owner:String!, $name:String!) {
                        repository(owner:$owner, name:$name){
                          issues(first:100, labels: [$label]) {
                            nodes {
                              id
                            }
                          }
                        }
                      }`;
                      const variables = {
                        owner: context.repo.owner,
                        name: context.repo.repo,
                        label: 'wontfix'
                      }
                      const result = await github.graphql(query, variables)
                      console.log(result)
          workflows:
            your-workflow:
              jobs:
                - your-job
    commands:
      script:
        description: "Run a script with octokit"
        parameters:
          github-token:
            description: "name of the environment variable containing the Github access token"
            type: string
            default: "GITHUB_TOKEN"
          script:
            description: "script to execute"
            type: string
        steps:
          - run:
              name: "Install @octokit/rest"
              command: |
                mkdir ./.orbspace/octokit -p

                cd ./.orbspace/octokit

                npm install @octokit/rest
          - run:
              name: "Prepare javascript application"
              command: |
                mkdir ./.orbspace/octokit -p

                echo '{}' \
                    | jq ". + {\"payload\": (.payload + {\"repo\": {\"owner\": \"${CIRCLE_PROJECT_USERNAME}\", \"repo\": \"${CIRCLE_PROJECT_REPONAME}\"}})}" \
                    | jq ". + {\"payload\": (.payload + {\"sender\": {\"login\": \"${CIRCLE_USERNAME}\"}})}" \
                    | jq "if \"${CIRCLE_PULL_REQUEST}\" == \"\" then . else (. + {\"payload\": (.payload + ({\"issue\": {\"number\": (\"${CIRCLE_PULL_REQUEST}\" | sub(\"/ *$\";\"\") | split(\"/\")[-1] | tonumber)}}))}) end" \
                    | jq "if .payload | has(\"issue\") then (. + {\"payload\": (.payload + {\"issue\": (.payload.issue + .payload.repo)})}) else . end" \
                    | jq "if \"${CIRCLE_PULL_REQUEST}\" == \"\" then . else (. + {\"payload\": (.payload + ({\"pull_request\": {\"number\": (\"${CIRCLE_PULL_REQUEST}\" | sub(\"/ *$\";\"\") | split(\"/\")[-1]) | tonumber}}))}) end" \
                    | jq "if .payload | has(\"pull_request\") then (. + {\"payload\": (.payload + {\"pull_request\": (.payload.pull_request + .payload.repo)})}) else . end" \
                    | jq ". + {\"sha\": \"${CIRCLE_SHA1}\"}" \
                    | jq ". + {\"ref\": \"${CIRCLE_BRANCH}\"}" \
                    | jq ". + {\"author\": \"${CIRCLE_USERNAME}\"}" \
                    | jq ". + {\"job\": \"${CIRCLE_JOB}\"}" \
                    | jq ". + {\"runNumber\": ${CIRCLE_BUILD_NUM}}" \
                    | jq ". + .payload" \
                    > ./.orbspace/octokit/context.json

                cat > ./.orbspace/octokit/script.js \<<'_EOF'
                exports.script = async function (github, context) { << parameters.script >>;
                };
                _EOF

                cat > ./.orbspace/octokit/app.js \<<'_EOF'
                import { Octokit } from "@octokit/rest";

                require("./script.js")
                  .script(
                    new Octokit({
                      auth: process.env['<< parameters.github-token >>']
                    }),
                    require("./context.json")
                  )
                ;
                _EOF

                cat ./.orbspace/octokit/context.json | jq '.'

          - run:
              name: "Execute javascript"
              command: |
                node --trace-warnings ./.orbspace/octokit/app.js

references:
  defaults: &defaults

jobs:
  test-context-with-pull-request:
    docker:
      - image: circleci/node
    steps:
      - run: |
          echo "export CIRCLE_BRANCH=feat/branch" >> $BASH_ENV
          echo "export CIRCLE_BUILD_NUM=123" >> $BASH_ENV
          echo "export CIRCLE_JOB=test" >> $BASH_ENV
          echo "export CIRCLE_PROJECT_REPONAME=Octo" >> $BASH_ENV
          echo "export CIRCLE_PROJECT_USERNAME=Github" >> $BASH_ENV
          echo "export CIRCLE_PULL_REQUEST=https://github.com/Github/Octo/pull/404" >> $BASH_ENV
          echo "export CIRCLE_SHA1=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" >> $BASH_ENV
          echo "export CIRCLE_USERNAME=PedroTroller" >> $BASH_ENV
      - octokit/script:
          script: |
            fs = require('fs');
            fs.writeFile(
              '/tmp/context.json',
              JSON.stringify(context),
              () => {}
            );
      - run: cat /tmp/context.json | jq '.'
      - run: cat /tmp/context.json | jq -e ".issue.number == 404"
      - run: cat /tmp/context.json | jq -e ".repo.owner == \"Github\""
      - run: cat /tmp/context.json | jq -e ".repo.repo == \"Octo\""
      - run: cat /tmp/context.json | jq -e ".payload.sender.login == \"PedroTroller\""
  test-context-without-pull-request:
    docker:
      - image: circleci/node
    steps:
      - run: |
          echo "export CIRCLE_BRANCH=feat/branch" >> $BASH_ENV
          echo "export CIRCLE_BUILD_NUM=123" >> $BASH_ENV
          echo "export CIRCLE_JOB=test" >> $BASH_ENV
          echo "export CIRCLE_PROJECT_REPONAME=Octo" >> $BASH_ENV
          echo "export CIRCLE_PROJECT_USERNAME=Github" >> $BASH_ENV
          echo "export CIRCLE_SHA1=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" >> $BASH_ENV
          echo "export CIRCLE_USERNAME=PedroTroller" >> $BASH_ENV
          echo "unset CIRCLE_PULL_REQUEST" >> $BASH_ENV
      - octokit/script:
          script: |
            fs = require('fs');
            fs.writeFile(
              '/tmp/context.json',
              JSON.stringify(context),
              () => {}
            );
      - run: cat /tmp/context.json | jq '.'
      - run: cat /tmp/context.json | jq -e ". | has(\"issue\") == false"
      - run: cat /tmp/context.json | jq -e ".payload | has(\"issue\") == false"
      - run: cat /tmp/context.json | jq -e ".repo.owner == \"Github\""
      - run: cat /tmp/context.json | jq -e ".repo.repo == \"Octo\""
      - run: cat /tmp/context.json | jq -e ".payload.sender.login == \"PedroTroller\""
  orb-build:
    docker:
      - image: mikefarah/yq
    steps:
      - checkout
      - run: yq read .circleci/config.yml 'orbs.octokit' | yq write - version $(yq read .circleci/config.yml version) > @orb.yml
      - persist_to_workspace:
          root: .
          paths:
            - "@orb.yml"
  orb-validate:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - cli/install
      - run: circleci orb validate @orb.yml
  release-check:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - cli/install
      - run:
          name: Check CircleCI CLI
          command: circleci orb --help
      - run: npx semantic-release --dry-run
  release-publish:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm install
      - cli/install
      - run: npx semantic-release

workflows:
  main:
    jobs:
      - test-context-with-pull-request
      - test-context-without-pull-request
      - orb-build:
          requires:
            - test-context-with-pull-request
            - test-context-without-pull-request
      - orb-validate:
          requires:
            - orb-build
      - release-check:
          requires:
            - orb-validate
      - release-publish:
          requires:
            - release-check
          filters:
            branches:
              only:
                - main
